// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVtRKRECSS9tZx3Bxu7WTTho09RRBZ1dY',
    appId: '1:89134818303:web:057a4d672c16c38af03dca',
    messagingSenderId: '89134818303',
    projectId: 'attendance-app-14519',
    authDomain: 'attendance-app-14519.firebaseapp.com',
    storageBucket: 'attendance-app-14519.firebasestorage.app',
    measurementId: 'G-YM3800L84T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CpDJxTSS5h_AlfqzlY6r6jIOX4IaqEg',
    appId: '1:89134818303:android:b30afbede2254b12f03dca',
    messagingSenderId: '89134818303',
    projectId: 'attendance-app-14519',
    storageBucket: 'attendance-app-14519.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3kp6NcDPawY3gjD5hGRQBJ6j4Z9o6J3k',
    appId: '1:89134818303:ios:ca160ab9e06fa077f03dca',
    messagingSenderId: '89134818303',
    projectId: 'attendance-app-14519',
    storageBucket: 'attendance-app-14519.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3kp6NcDPawY3gjD5hGRQBJ6j4Z9o6J3k',
    appId: '1:89134818303:ios:ca160ab9e06fa077f03dca',
    messagingSenderId: '89134818303',
    projectId: 'attendance-app-14519',
    storageBucket: 'attendance-app-14519.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVtRKRECSS9tZx3Bxu7WTTho09RRBZ1dY',
    appId: '1:89134818303:web:589ceadfbb1c1815f03dca',
    messagingSenderId: '89134818303',
    projectId: 'attendance-app-14519',
    authDomain: 'attendance-app-14519.firebaseapp.com',
    storageBucket: 'attendance-app-14519.firebasestorage.app',
    measurementId: 'G-4JLRFD9EXJ',
  );
}
